CREATE TABLE patients (
id INT GENERATED ALWAYS AS IDENTITY,
name VARCHAR(250) NOT NULL,
date_of_birth DATE NOT NULL,
PRIMARY KEY(id) );

CREATE TABLE medical_histories (
id INT GENERATED ALWAYS AS IDENTITY,
admitted_at TIMESTAMP,
patient_id INT NOT NULL,
status VARCHAR(250) NOT NULL, 
PRIMARY KEY(id),
FOREIGN KEY(patient_id)
REFERENCES patients (id)
ON DELETE CASCADE
);

CREATE TABLE treatments (
id INT GENERATED ALWAYS AS IDENTITY,
type VARCHAR(250) NOT NULL,
name VARCHAR(250) NOT NULL,
PRIMARY KEY(id) );